ministryofjustice/check-my-diary

helm_deploy/check-my-diary-prod/templates/cron.yaml
helm_deploy/check-my-diary-prod/templates/variables.yaml
helm_deploy/check-my-diary-prod/values.yaml

VERY rough, how we do cron jobs needs refactoring before go live proper

awful piece of work for multi region cronjob support to get through POC

---

helm_deploy/check-my-diary-dev/README.md

dummy changes to trigger the pipeline

Testing the circleci pipeline

---

helm_deploy/check-my-diary/templates/deployment.yaml
helm_deploy/check-my-diary/templates/ingress.yaml

Reverts ministryofjustice/check-my-diary#80

Revert "DT-917: Switch out deprecated APIs"

---

helm_deploy/check-my-diary/templates/deployment.yaml
helm_deploy/check-my-diary/templates/ingress.yaml

Reverts ministryofjustice/check-my-diary#82

Revert "Revert "DT-917: Switch out deprecated APIs""

---

server/app.js
server/index.js
server/routes/calendar.js
server/routes/calendar.test.js
server/routes/notification.js
server/services/DEPRECATEnotificationService.js

**Changes:**
- rename service in preparation for replacement

🚚 rename notificationService -> DEPRECATEnotificationService

---

.eslintignore
config.js
integration-tests/mockApis/notificationService.js
integration-tests/plugins/index.js
integration-tests/wiremock-tests/notifcation-service.test.js
jest.config.integration.json
jest.config.json
package.json
server/app.js
server/index.js
server/routes/calendar.js
server/routes/calendar.test.js
server/routes/notification.js
server/services/DEPRECATEnotificationService.js
server/services/notificationService.js

**MERGE #98 first**
**Changes:**
- create skeleton for notifications service
- setup jest to run integrations tests
- setup wiremock for notifications service with dummy test

🏗 Setup notifications service skeleton with integration tests

---

server/app.js
server/index.js
server/routes/calendar.js
server/routes/calendar.test.js
server/routes/notification.js
server/services/DEPRECATEnotificationService.js

**Changes:**
- rename service in preparation for replacement

🚚 rename notificationService -> DEPRECATE_notificationService

---

server/app.js
server/middleware/tokenRefresh.js

**Changes:**
- refactor refresh token middleware to own file

♻️ refactor refresh token middleware

---

server/app.js
server/index.js
server/routes/calendar-detail.js
server/routes/calendar-detail.test.js
server/routes/calendar.js
server/routes/calendar.test.js
server/routes/testutils/appSetup.js
server/services/calendarService.js

**Changes:**
- ♻️ refactor service to be methods
- 🔧 remove calendarService from function scope and add as server config…
- ♻️ update routes to access calendarService from app.get
- ✅ fix tests to add mocked function via server config

♻️ Configure server to add calendar service to app

---

server/app.js
server/index.js
server/routes/calendar-detail.js
server/routes/calendar-detail.test.js
server/routes/calendar.js
server/routes/calendar.test.js
server/routes/notification.js
server/services/DEPRECATEnotificationService.js
server/services/calendarOvertimeService.js

**Changes:**
- refactor all services to be methods
- add services to app

♻️ add all services to app

---

server/app.js
server/authentication/auth.js
server/middleware/authHandlerMiddleware.js
server/middleware/authenticationMiddleware.js
server/middleware/csrfTokenMiddleware.js
server/routes/standardRouter.js
server/routes/testutils/mockAuthentication.js

**Changes:**
- pull out authentication middleware to own file
- pull out auth handler middleware
- pull out csrf token middleware

♻️ Refactor middleware

---

server/views/pages/notifications.ejs
server/views/partials/header.ejs

We actually want to be able to access the notification preferences regardless

🐛 Take MFA checks out

---

server/views/pages/notifications.ejs
server/views/partials/snooze-banner.ejs
server/views/partials/summary.ejs

its now normal, remove the red banner from the text

💄 'No notifications' is not a warning situation

---

integration-tests/integration/calendar-overtime.spec.js
integration-tests/integration/calendar.spec.js
integration-tests/integration/notifications.spec.js
integration-tests/mockApis/notificationService.js
integration-tests/plugins/index.js
server/views/partials/snooze-banner.ejs

**Changes:**
- very basic tests for notifications page
- fix mocks
- stub notification calls in other integration tests

✅ add integration tests for notifications page

---

helm_deploy/check-my-diary/templates/autoscale.yaml

🔧  Increase minimum pod count on HPA

---

integration-tests/mockApis/notificationService.js
server/middleware/notificationMiddleware.test.js

🤠 test that started failing due to not mocked dependency and ropey test data 😬

🐛✅notification-tests-fix

---

helm_deploy/check-my-diary/Chart.yaml
helm_deploy/check-my-diary/values.yaml

PAT-1898 Implement generic service chart - fix

---

helm_deploy/check-my-diary/Chart.yaml
helm_deploy/check-my-diary/values.yaml
package-lock.json

Also upgraded tar and generic service version

Pat 2018 tune kubernetes autoscaler to avoid alerts in prod

---

package-lock.json

🔐 Fix Json Schema Security Vulnerability

🔐 Fix Json Schema Security Vulnerability

---

package-lock.json

🤖 PAT-2140: Fix Security Vulnerabilities

🤖 PAT-2140: Fix Security Vulnerabilities

---

.gitignore
assets/sass/_header.scss

More tweak requests from Eddie in testing

SDI-136 Updates to black header bar

---

integration_tests/e2e/calendar.cy.ts
server/middleware/calendarMiddleware.js

AC change - just show when SMS set

SDI-183 CMD - Notifications banner for text message switch off

---

assets/sass/_calendar.scss
server/controllers/calendarController.test.ts
server/helpers/utilities.js
server/helpers/utilities.test.ts
server/helpers/utilities.types.ts
server/views/helpers/helpers.ejs
server/views/pages/calendar.ejs

SDI-168 Calendar screen - MOBILE UI & content changes

---

assets/sass/_calendar.scss
integration_tests/e2e/calendar-overtime.cy.ts
integration_tests/e2e/calendar.cy.ts
integration_tests/pages/calendarPage.ts
server/helpers/utilities.ts
server/helpers/utilities.types.ts
server/views/pages/calendar.njk

Tweaks to complete desktop design

SDI-275 CMD - Pre existing issues

---

assets/sass/_calendar.scss
server/helpers/utilities.ts
server/helpers/utilities.types.ts
server/views/pages/calendar.njk

SDI-115 Calendar screen - DESKTOP UI & content changes

---

assets/sass/_calendar.scss

SDI-115 calendar screen desktop UI & content changes

---

integration_tests/e2e/login.cy.ts
server/routes/standardRouter.ts

QA fix - redirect old endpoints

SDI-329 Remove unused UI code

---

integration_tests/e2e/calendar.cy.ts
server/views/pages/calendar.njk

Reverts ministryofjustice/check-my-diary#383

Revert "SDI-322 Remove ability to send notification texts"

---

integration_tests/e2e/calendar.cy.ts
server/config.ts
server/controllers/calendarController.ts
server/routes/index.ts

Show DPS link based on param - fix

SDI-324 Add CMD tile to DPS & navigation link to CMD homepage

---

integration_tests/e2e/notifications-settings.cy.ts
server/controllers/postNotificationSettingsController.ts
server/routes/notificationRouter.ts
server/views/pages/calendar.njk
server/views/pages/notification-settings.njk

QA fixes to [SDI-392](https://dsdmoj.atlassian.net/browse/SDI-392)

SDI-407 Amend notifications/settings content

---

server/views/pages/calendar.njk

SDI-392 CMD banner changes

---

assets/scss/_mixins.scss

Aims to remove the "double crest" thats appearing with the new implementation of the MOJ Header

Removed crest in header

---

server/views/pages/calendar.njk

Added "beforeContent" block for DPS breadcrumb link

Updated header to match other pages. 

---

server/routes/index.test.ts
server/views/pages/contact-us.njk
server/views/partials/footer.njk

This PR fixes some of the content on the Contact us page - the changes are minimal and include:
* updating product name to be accurate
* updating email link to be more standard
* updating Footer link to be more accurate
* fixing tests to look for new wording

Small update to contact page
